"""Bit-identical env golden-parity gate — training-speedup-v2 Step 1.

THE load-bearing regression guard for every speedup stage. Two gates
(hard_constraints #1):

* **GATE (a) — reproduction / self-parity.** The CURRENT canonical
  sequential env (`RolloutCollector` + predictors-ON `BetfairEnv`) must
  reproduce the committed golden fixtures bit-for-bit (discrete exact,
  continuous within declared per-quantity tolerance). If this fails, the
  env behaviour changed (or capture went nondeterministic) — investigate
  before trusting any speedup.
* **GATE (b) — discrimination.** A deliberately-injected **1-tick price
  perturbation** in the matcher must be CAUGHT. Proves the harness
  actually discriminates a small logic divergence and isn't so loose it
  would miss the kind of bug this whole plan exists to catch.

Fixtures live in ``tests/fixtures/golden/`` and are (re)generated by
``python -m tools.gen_golden_fixtures``. They are tied to (env config +
policy arch + seed); regenerate them deliberately if the *intended* env
behaviour changes, never to silence a red gate (HC#7: golden is right).

Marked ``slow`` — builds predictors-ON envs (~5 s each). Run with
``pytest tests/test_env_golden_parity.py -m slow``.
"""
from __future__ import annotations

import dataclasses
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "golden"
_PRED = REPO_ROOT.parent / "betfair-predictors" / "production"
_DATA = REPO_ROOT / "data" / "processed"

# Skip the whole module if the predictor bundle or data isn't present
# (e.g. a CI box without the sibling betfair-predictors checkout).
_requires_assets = pytest.mark.skipif(
    not (_PRED / "race-outcome" / "manifest.json").exists()
    or not _DATA.exists()
    or not FIXTURE_DIR.exists(),
    reason="predictor bundle / processed data / golden fixtures not present",
)

pytestmark = [pytest.mark.slow, _requires_assets]


from env.exchange_matcher import ExchangeMatcher, MatchResult  # noqa: E402
from env.tick_ladder import tick_offset  # noqa: E402
from training_v2.cohort.static_obs_cache import DayStaticObs  # noqa: E402
from training_v2.golden_cases import CASES, build_env, build_policy  # noqa: E402
from training_v2.golden_parity import (  # noqa: E402
    capture_golden,
    capture_golden_from_batched,
    compare_streams,
    load_stream,
)


def _capture_case(case):
    env, shim = build_env(case.env_config, day=case.day, n_races=case.n_races)
    policy = build_policy(shim, hidden=case.hidden, seed=case.seed)
    return capture_golden(shim, policy, seed=case.seed, case=case.name)


# ── GATE (a): current env reproduces every committed golden fixture ───────


@pytest.mark.parametrize("case", CASES, ids=[c.name for c in CASES])
def test_current_env_matches_golden_fixture(case):
    fixture = FIXTURE_DIR / case.name
    if not fixture.with_suffix(".npz").exists():
        pytest.skip(f"fixture {case.name} not generated")
    golden = load_stream(fixture)
    fresh = _capture_case(case)
    diffs = compare_streams(golden, fresh, label=case.name)
    assert not diffs, (
        f"GATE (a) FAIL: current env diverged from golden '{case.name}':\n"
        + "\n".join(f"  {d}" for d in diffs[:20])
    )


# ── GATE (b): a deliberately-injected 1-tick perturbation is CAUGHT ───────


class _OneTickMatcher:
    """Context manager: shift every successful fill by one tick.

    Patches ``ExchangeMatcher._match`` (the shared core of match_back /
    match_lay) so any non-zero fill returns ``average_price`` one tick
    worse. A genuine end-to-end perturbation: it flows obs → policy →
    matching → reward → settle, exactly where a real off-by-one bug
    would live.
    """

    def __enter__(self):
        self._orig = ExchangeMatcher._match

        def patched(matcher_self, *args, **kwargs):
            res = self._orig(matcher_self, *args, **kwargs)
            if res.matched_stake > 0.0 and res.average_price > 1.0:
                bumped = tick_offset(res.average_price, 1, +1)
                return dataclasses.replace(res, average_price=bumped)
            return res

        ExchangeMatcher._match = patched
        return self

    def __exit__(self, *exc):
        ExchangeMatcher._match = self._orig
        return False


def test_harness_catches_injected_one_tick_perturbation():
    # A case that actually places bets, so the perturbation has something
    # to bite on.
    case = next(c for c in CASES if c.name == "normal_h128_s1")
    golden = _capture_case(case)
    assert len(golden.bets) > 0, "precondition: golden must place bets"

    with _OneTickMatcher():
        perturbed = _capture_case(case)

    diffs = compare_streams(golden, perturbed, label="one_tick")
    assert diffs, (
        "GATE (b) FAIL: harness did NOT catch a 1-tick matcher "
        "perturbation — it is not discriminating."
    )
    # And the very first thing it should notice is a price/PnL drift on a
    # matched bet (not merely some incidental downstream wobble).
    quantities = {d.quantity.split("[")[0].split(".")[0] for d in diffs}
    assert quantities & {"bet", "obs", "per_runner_reward", "value_per_runner",
                         "info", "pairing_structure", "bet_count"}, (
        f"unexpected mismatch surface: {[str(d) for d in diffs[:5]]}"
    )


def test_perturbation_recovers_when_matcher_restored():
    """Control: without the patch, the same case reproduces (no false
    alarm from the perturbation machinery leaking)."""
    case = next(c for c in CASES if c.name == "normal_h128_s1")
    a = _capture_case(case)
    b = _capture_case(case)
    assert not compare_streams(a, b), "self-parity broke outside the patch"


# ── Step 3A gate: the BATCHED fast path reproduces the golden ─────────────


@pytest.mark.parametrize(
    "case_name", ["normal_h128_s1", "forceclose_h128_s1"],
)
def test_batched_path_matches_golden_fixture(case_name):
    """The CPU batched collector (N=1, seeds=None → single-global-RNG
    path) must reproduce the canonical solo golden bit-for-bit. Gates
    the Step-3A batched changes (CPU-rollout + feature_cache) against the
    same harness the solo path is gated on (HC#1/#2/#7)."""
    case = next(c for c in CASES if c.name == case_name)
    fixture = FIXTURE_DIR / case.name
    if not fixture.with_suffix(".npz").exists():
        pytest.skip(f"fixture {case.name} not generated")
    golden = load_stream(fixture)
    env, shim = build_env(case.env_config, day=case.day, n_races=case.n_races)
    policy = build_policy(shim, hidden=case.hidden, seed=case.seed)
    batched = capture_golden_from_batched(
        shim, policy, seed=case.seed, case=case.name, device="cpu",
    )
    # The BatchedRolloutCollector does not stamp per-bet aux-head decision
    # values (fill/mature/direction _at_placement) — a PRE-EXISTING gap vs
    # the solo collector's "v2-aux-head-bet-plumbing", orthogonal to the
    # Step-3A CPU-rollout/feature_cache changes under test. Exclude those
    # forensic fields; every load-bearing quantity must still match.
    aux_stamp_fields = frozenset({
        "fill_prob_at_placement", "mature_prob_at_placement",
        "direction_back_prob_at_placement", "direction_lay_prob_at_placement",
    })
    # R1: batched_forward_core uses the vmap-able MANUAL LSTM, which differs
    # from the golden's fused nn.LSTM by float-reordering that ACCUMULATES
    # through the recurrence. Looser-but-tight tols on the LSTM-affected
    # continuous quantities; DISCRETE actions stay exact (a flipped action
    # cascades into a different trajectory and must still trip the gate —
    # verified 0 flips on these cases).
    manual_lstm_tol = {
        "stake_unit": (0.0, 1e-4),
        "hidden_in": (1e-3, 5e-3),
        "log_prob_action": (1e-3, 1e-3),
        "log_prob_stake": (1e-3, 1e-3),
        "value_per_runner": (0.0, 1e-3),
    }
    diffs = compare_streams(
        golden, batched, label=f"batched:{case.name}",
        ignore_bet_fields=aux_stamp_fields,
        tol_override=manual_lstm_tol,
    )
    assert not diffs, (
        f"GATE FAIL: batched path diverged from golden '{case.name}' on a "
        f"load-bearing quantity:\n"
        + "\n".join(f"  {d}" for d in diffs[:20])
    )


# ── shared-memory-day-cache gate: the static_obs memmap path == from-scratch ─


@pytest.mark.parametrize(
    "case_name",
    ["normal_h128_s1", "gated_h128_s2", "forceclose_h128_s1"],
)
def test_static_obs_cache_path_matches_from_scratch(case_name, tmp_path):
    """The shared-memory ``static_obs`` path reproduces the from-scratch env
    bit-for-bit (shared-memory-day-cache HC#1).

    A worker that consumes the pre-baked :class:`DayStaticObs` artifact
    (memmapped ``static_obs`` arrays + sidecar predictor gate caches) must
    produce the SAME obs → action → match → reward → settle stream as the
    canonical ``engineer_day`` + ``_features_to_array`` + per-worker
    predictor-inference path. We capture both and compare directly (no
    committed fixture needed): cache-path == from-scratch, and GATE (a)
    already pins from-scratch == fixture.

    Cases exercise a normal day, a **predictor-gated** day (proves the
    cached ``_race_p_win_by_race`` / ``_tick_drift_fires_by_race`` gate
    caches drive the same gate decisions) and a **force-close** day.
    """
    case = next(c for c in CASES if c.name == case_name)

    # 1. From-scratch env → extract + persist the artifact while pristine.
    src_env, src_shim = build_env(
        case.env_config, day=case.day, n_races=case.n_races,
    )
    artifact = DayStaticObs.from_env(src_env)
    npy = tmp_path / f"static_obs_{case.day}.npy"
    side = tmp_path / f"meta_{case.day}.pkl"
    artifact.save(npy, side)
    loaded = DayStaticObs.load(npy, side, mmap=True)
    # HC#2: the shared array is read-only (a worker mutation corrupts siblings).
    assert not loaded.static_obs_flat.flags.writeable, (
        "memmapped static_obs must be read-only"
    )

    # 2. Capture the from-scratch stream (env is pristine post-extraction —
    #    extraction only reads precompute outputs).
    src_policy = build_policy(src_shim, hidden=case.hidden, seed=case.seed)
    golden_fresh = capture_golden(
        src_shim, src_policy, seed=case.seed, case=case.name,
    )

    # 3. Cache-consuming env → capture its stream.
    env, shim = build_env(
        case.env_config, day=case.day, n_races=case.n_races,
        static_obs_cache={case.day: loaded},
    )
    cached = capture_golden(
        shim, build_policy(shim, hidden=case.hidden, seed=case.seed),
        seed=case.seed, case=case.name,
    )

    diffs = compare_streams(
        golden_fresh, cached, label=f"static_obs:{case.name}",
    )
    assert not diffs, (
        f"GATE FAIL: static_obs cache path diverged from from-scratch "
        f"'{case.name}':\n" + "\n".join(f"  {d}" for d in diffs[:20])
    )
