"""Bit-identical env golden-parity gate — training-speedup-v2 Step 1.

THE load-bearing regression guard for every speedup stage. Two gates
(hard_constraints #1):

* **GATE (a) — reproduction / self-parity.** The CURRENT canonical
  sequential env (`RolloutCollector` + predictors-ON `BetfairEnv`) must
  reproduce the committed golden fixtures bit-for-bit (discrete exact,
  continuous within declared per-quantity tolerance). If this fails, the
  env behaviour changed (or capture went nondeterministic) — investigate
  before trusting any speedup.
* **GATE (b) — discrimination.** A deliberately-injected **1-tick price
  perturbation** in the matcher must be CAUGHT. Proves the harness
  actually discriminates a small logic divergence and isn't so loose it
  would miss the kind of bug this whole plan exists to catch.

Fixtures live in ``tests/fixtures/golden/`` and are (re)generated by
``python -m tools.gen_golden_fixtures``. They are tied to (env config +
policy arch + seed); regenerate them deliberately if the *intended* env
behaviour changes, never to silence a red gate (HC#7: golden is right).

Marked ``slow`` — builds predictors-ON envs (~5 s each). Run with
``pytest tests/test_env_golden_parity.py -m slow``.
"""
from __future__ import annotations

import dataclasses
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "golden"
_PRED = REPO_ROOT.parent / "betfair-predictors" / "production"
_DATA = REPO_ROOT / "data" / "processed"

# Skip the whole module if the predictor bundle or data isn't present
# (e.g. a CI box without the sibling betfair-predictors checkout).
_requires_assets = pytest.mark.skipif(
    not (_PRED / "race-outcome" / "manifest.json").exists()
    or not _DATA.exists()
    or not FIXTURE_DIR.exists(),
    reason="predictor bundle / processed data / golden fixtures not present",
)

pytestmark = [pytest.mark.slow, _requires_assets]


from env.exchange_matcher import ExchangeMatcher, MatchResult  # noqa: E402
from env.tick_ladder import tick_offset  # noqa: E402
from training_v2.golden_cases import CASES, build_env, build_policy  # noqa: E402
from training_v2.golden_parity import (  # noqa: E402
    capture_golden,
    compare_streams,
    load_stream,
)


def _capture_case(case):
    env, shim = build_env(case.env_config, day=case.day, n_races=case.n_races)
    policy = build_policy(shim, hidden=case.hidden, seed=case.seed)
    return capture_golden(shim, policy, seed=case.seed, case=case.name)


# ── GATE (a): current env reproduces every committed golden fixture ───────


@pytest.mark.parametrize("case", CASES, ids=[c.name for c in CASES])
def test_current_env_matches_golden_fixture(case):
    fixture = FIXTURE_DIR / case.name
    if not fixture.with_suffix(".npz").exists():
        pytest.skip(f"fixture {case.name} not generated")
    golden = load_stream(fixture)
    fresh = _capture_case(case)
    diffs = compare_streams(golden, fresh, label=case.name)
    assert not diffs, (
        f"GATE (a) FAIL: current env diverged from golden '{case.name}':\n"
        + "\n".join(f"  {d}" for d in diffs[:20])
    )


# ── GATE (b): a deliberately-injected 1-tick perturbation is CAUGHT ───────


class _OneTickMatcher:
    """Context manager: shift every successful fill by one tick.

    Patches ``ExchangeMatcher._match`` (the shared core of match_back /
    match_lay) so any non-zero fill returns ``average_price`` one tick
    worse. A genuine end-to-end perturbation: it flows obs → policy →
    matching → reward → settle, exactly where a real off-by-one bug
    would live.
    """

    def __enter__(self):
        self._orig = ExchangeMatcher._match

        def patched(matcher_self, *args, **kwargs):
            res = self._orig(matcher_self, *args, **kwargs)
            if res.matched_stake > 0.0 and res.average_price > 1.0:
                bumped = tick_offset(res.average_price, 1, +1)
                return dataclasses.replace(res, average_price=bumped)
            return res

        ExchangeMatcher._match = patched
        return self

    def __exit__(self, *exc):
        ExchangeMatcher._match = self._orig
        return False


def test_harness_catches_injected_one_tick_perturbation():
    # A case that actually places bets, so the perturbation has something
    # to bite on.
    case = next(c for c in CASES if c.name == "normal_h128_s1")
    golden = _capture_case(case)
    assert len(golden.bets) > 0, "precondition: golden must place bets"

    with _OneTickMatcher():
        perturbed = _capture_case(case)

    diffs = compare_streams(golden, perturbed, label="one_tick")
    assert diffs, (
        "GATE (b) FAIL: harness did NOT catch a 1-tick matcher "
        "perturbation — it is not discriminating."
    )
    # And the very first thing it should notice is a price/PnL drift on a
    # matched bet (not merely some incidental downstream wobble).
    quantities = {d.quantity.split("[")[0].split(".")[0] for d in diffs}
    assert quantities & {"bet", "obs", "per_runner_reward", "value_per_runner",
                         "info", "pairing_structure", "bet_count"}, (
        f"unexpected mismatch surface: {[str(d) for d in diffs[:5]]}"
    )


def test_perturbation_recovers_when_matcher_restored():
    """Control: without the patch, the same case reproduces (no false
    alarm from the perturbation machinery leaking)."""
    case = next(c for c in CASES if c.name == "normal_h128_s1")
    a = _capture_case(case)
    b = _capture_case(case)
    assert not compare_streams(a, b), "self-parity broke outside the patch"
