"""views.py — Engelbart-style view control (v3 Phase H). Stdlib only.

Generated **views over the projection** — selective level-clipping / filtering / transformation of what
you see (OHS "view control") — rendered to markdown (and a minimal HTML) **with zero Obsidian
dependency and the LLM off**. Views are pure `projection → template`: disposable artifacts written to
`out/` (gitignored), regenerable from the DB at any time. They are never the source of truth and never
call the model.

Views:
  verified-only          claims human/cross-source verified
  unverified-claims      model-asserted, still-unverified claims (the hallucination-risk flag)
  dialog-trail <id>      how a conclusion was reached (walks the CoDIAK dialog record)
  supersession-timeline  what superseded what, over time
  draft-vs-stable        the lifecycle view (notes by status)
"""
from __future__ import annotations

import html as _html
from pathlib import Path

import projection as _p
import wiki_tool as wt


# --------------------------------------------------------------------------- #
# tiny markdown helpers + a minimal markdown -> HTML (no dependency)
# --------------------------------------------------------------------------- #
def _table(headers, rows):
    if not rows:
        return "_(none)_\n"
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out) + "\n"


def md_to_html(md: str, title: str = "view") -> str:
    """Render the constrained markdown the views emit (headings, tables, lists, paras) to HTML."""
    lines = md.splitlines()
    body, i = [], 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("### "):
            body.append(f"<h3>{_html.escape(ln[4:])}</h3>")
        elif ln.startswith("## "):
            body.append(f"<h2>{_html.escape(ln[3:])}</h2>")
        elif ln.startswith("# "):
            body.append(f"<h1>{_html.escape(ln[2:])}</h1>")
        elif ln.startswith("| "):                       # a markdown table block
            tbl = []
            while i < len(lines) and lines[i].startswith("|"):
                tbl.append(lines[i])
                i += 1
            cells = [[c.strip() for c in row.strip("|").split("|")] for row in tbl]
            rows = [r for r in cells if not all(set(c) <= set("-: ") for c in r)]
            body.append("<table border=1 cellpadding=4 cellspacing=0>")
            for n, r in enumerate(rows):
                tag = "th" if n == 0 else "td"
                body.append("<tr>" + "".join(f"<{tag}>{_html.escape(c)}</{tag}>" for c in r) + "</tr>")
            body.append("</table>")
            continue
        elif ln.startswith("- "):
            body.append(f"<li>{_html.escape(ln[2:])}</li>")
        elif ln.strip() == "":
            body.append("")
        else:
            body.append(f"<p>{_html.escape(ln)}</p>")
        i += 1
    return (f"<!doctype html><html><head><meta charset=utf-8><title>{_html.escape(title)}</title>"
            "<style>body{font-family:system-ui,sans-serif;max-width:60rem;margin:2rem auto;padding:0 1rem}"
            "table{border-collapse:collapse}th{background:#f0f0f0}</style></head><body>\n"
            + "\n".join(body) + "\n</body></html>\n")


_HEADER = "_Generated by `wiki_tool view` from the projection — no LLM, no Obsidian._"


# --------------------------------------------------------------------------- #
# the views — each returns markdown
# --------------------------------------------------------------------------- #
def view_verified_only(con, public=False):
    rows = _p.q_verified_claims(con, public=public)
    md = ["# View: verified-only", "", _HEADER, "",
          f"{len(rows)} human/cross-source-verified claim(s).", "",
          _table(["claim", "note", "text", "verified_by"],
                 [(r["id"], r["note_path"], r["text"], r["verified_by"]) for r in rows])]
    return "\n".join(md)


def view_unverified_claims(con, public=False):
    rows = _p.q_flagged_claims(con, public=public)
    md = ["# View: unverified-claims", "", _HEADER, "",
          "Model-asserted claims **not yet verified** — treat as hallucination-risk until checked.", "",
          f"{len(rows)} flagged claim(s).", "",
          _table(["claim", "note", "text", "asserted_by"],
                 [(r["id"], r["note_path"], r["text"], r["asserted_by"]) for r in rows])]
    return "\n".join(md)


def view_dialog_trail(con, of=None, public=False):
    if not of:
        raise ValueError("dialog-trail requires --of <conclusion/claim/event id>")
    rows = _p.q_dialog_trail(con, of, public=public)
    md = ["# View: dialog-trail", "", _HEADER, "",
          f"How conclusion `{of}` was reached — {len(rows)} event(s), oldest first:", ""]
    for r in rows:
        md.append(f"- **{r['kind']}** ({r['ts']}, {r['author']}) — {r['text']}")
        links = r.get("links")
        if isinstance(links, str):
            import json
            links = json.loads(links) if links else []
        if links:
            md.append(f"  - concerns: {', '.join(links)}")
    if not rows:
        md.append("_(no dialog events reference that id)_")
    return "\n".join(md) + "\n"


def view_supersession_timeline(con, public=False):
    pub = " AND newer.public=1 AND older.public=1" if public else ""
    rows = _p._rows(con,
                    f"SELECT newer.title AS superseding, newer.updated AS ts, older.title AS stale, "
                    f"older.id AS stale_id FROM links l "
                    f"JOIN objects newer ON newer.id=l.from_id JOIN objects older ON older.id=l.to_id "
                    f"WHERE l.type='supersedes'{pub} ORDER BY newer.updated, newer.title")
    md = ["# View: supersession-timeline", "", _HEADER, "",
          f"{len(rows)} supersession(s), oldest first. The stale side is superseded knowledge.", "",
          _table(["when", "superseding", "→ supersedes (stale)"],
                 [(r["ts"], r["superseding"], r["stale"]) for r in rows])]
    return "\n".join(md)


def view_draft_vs_stable(con, public=False):
    pub = " WHERE public=1" if public else ""
    rows = _p._rows(con, f"SELECT status, title, path, verification FROM objects{pub} "
                         f"ORDER BY status, title")
    md = ["# View: draft-vs-stable", "", _HEADER, ""]
    by_status = {}
    for r in rows:
        by_status.setdefault(r["status"] or "(none)", []).append(r)
    for status in ("seed", "draft", "stable", "(none)"):
        group = by_status.get(status)
        if not group:
            continue
        md.append(f"## {status} ({len(group)})")
        md.append(_table(["title", "verification", "path"],
                         [(g["title"], g["verification"], g["path"]) for g in group]))
    return "\n".join(md)


VIEWS = {
    "verified-only": (view_verified_only, [], "claims human/cross-source verified"),
    "unverified-claims": (view_unverified_claims, [], "model-asserted, still-unverified claims"),
    "dialog-trail": (view_dialog_trail, ["of"], "how a conclusion was reached (--of <id>)"),
    "supersession-timeline": (view_supersession_timeline, [], "what superseded what, over time"),
    "draft-vs-stable": (view_draft_vs_stable, [], "notes by lifecycle status"),
}


def render(name, params=None, public=False, fmt="md", path=None) -> str:
    """Render a view to a string (markdown or html). Pure projection → template; never calls the LLM."""
    params = params or {}
    if name not in VIEWS:
        raise KeyError(f"unknown view '{name}' (known: {', '.join(sorted(VIEWS))})")
    fn, required, _help = VIEWS[name]
    for r in required:
        if not params.get(r):
            raise ValueError(f"view '{name}' requires --{r}")
    con = _p.connect_ro(path)
    try:
        import inspect
        accepted = set(inspect.signature(fn).parameters) - {"con", "public"}
        kwargs = {k: v for k, v in params.items() if v is not None and k in accepted}
        md = fn(con, public=public, **kwargs)
    finally:
        con.close()
    return md_to_html(md, title=name) if fmt == "html" else md


def out_dir() -> Path:
    return Path(wt.ROOT) / "out"


def render_to_file(name, params=None, public=False, fmt="md") -> Path:
    """Render a view and write it to the gitignored out/ dir. Returns the path."""
    content = render(name, params=params, public=public, fmt=fmt)
    d = out_dir()
    d.mkdir(parents=True, exist_ok=True)
    suffix = "html" if fmt == "html" else "md"
    p = d / f"{name}.{suffix}"
    p.write_text(content, encoding="utf-8")
    return p
