"""Offline arb oracle scan — v2 stack.

Copy of ``training.arb_oracle`` adapted to the v2 ``DiscreteActionShim``
obs schema. The scan logic, junk filter, price caps, freed-budget rule
and determinism contract are unchanged from v1; the only difference is
how each sample's ``obs`` is constructed.

Why a copy and not a reuse: v2's policy is built against ``shim.obs_dim
= env.observation_space.shape[0] + 2 * max_runners`` — the shim appends
``2 * max_runners`` Phase 0 supervised-scorer features (calibrated
``P(mature | features)`` per (runner, side)) at every step. The v1
oracle constructs obs as ``static_obs || zero_agent_state || zero_pos``
which matches ``env.observation_space.shape[0]`` only — short by
``2 * max_runners`` floats for v2. The shim's rolling-window
``FeatureExtractor`` requires per-tick ``update_history`` calls in
order, so the obs cannot be built from a precomputed slice — we walk
each race forward and let the shim assemble the extended obs.

Hard constraints (``plans/rewrite/phase-8-oracle-bc-pretrain/
hard_constraints.md``):
- §1 Offline only. Never invoked inside the training loop.
- §2 Deterministic. Same date + same config + same scorer artefacts →
  byte-identical ``.npz`` output. Sort samples by
  ``(tick_index, runner_idx)`` before writing.
- §3 Env-reachable only. Each emitted sample passes the same junk
  filter, price caps, and budget checks the live matcher applies.
- §4 Cache header carries ``obs_schema_version`` AND ``obs_dim``;
  ``load_samples(strict=True)`` raises on either mismatch.

Cache lands in ``data/oracle_cache_v2/{date}/`` — distinct from v1's
``data/oracle_cache/{date}/`` so the two stacks can coexist on the
same processed-data directory without overwriting each other.

CLI::

    python -m training_v2.arb_oracle scan --date 2026-04-10
    python -m training_v2.arb_oracle scan --dates 2026-04-08,2026-04-09
"""

from __future__ import annotations

import json
import logging
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from agents_v2.env_shim import DEFAULT_SCORER_DIR, DiscreteActionShim
from env.betfair_env import (
    ACTION_SCHEMA_VERSION,
    AGENT_STATE_DIM,
    MAX_ARB_TICKS,
    OBS_SCHEMA_VERSION,
    POSITION_DIM,
    SCALPING_AGENT_STATE_DIM,
    SCALPING_POSITION_DIM,
    BetfairEnv,
)
from env.exchange_matcher import passes_junk_filter, passes_price_cap
from env.scalping_math import locked_pnl_per_unit_stake, min_arb_ticks_for_profit
from env.tick_ladder import tick_offset, ticks_between
from training_v2.scorer.feature_extractor import FeatureExtractor

logger = logging.getLogger(__name__)

# Betfair minimum bet — mirrors env._MIN_STAKE / bet_manager.MIN_BET_STAKE.
_MIN_STAKE: float = 2.0
# Default junk-filter tolerance — mirrors ExchangeMatcher default.
_DEFAULT_MAX_DEV_PCT: float = 0.5


@dataclass(slots=True)
class OracleSample:
    """One detected profitable-arb moment.

    ``obs`` is the v2 extended obs — ``env.observation_space.shape[0]
    + 2 * max_runners`` floats — ready to feed directly into a
    :class:`DiscreteLSTMPolicy` built with ``obs_dim = shim.obs_dim``.
    """

    tick_index: int        # global pre-race tick index across the day
    runner_idx: int        # runner slot (env's sorted-sid index)
    obs: np.ndarray        # float32, shape (shim.obs_dim,)
    arb_spread_ticks: int  # minimum tick spread for a profitable pair
    expected_locked_pnl: float  # locked P&L per unit of aggressive stake


@dataclass(slots=True)
class NegativeOracleSample:
    """One oracle-NEGATIVE moment — a (tick, runner) that is NOT in the
    positive arb set.

    BC label augmentation Phase A (``plans/bc-label-augmentation/``).
    The obs vector is constructed exactly the same way as a positive
    sample at that (tick, runner) — zero agent state, zero position,
    shim-extended scorer features. Downstream BC pretrain targets
    ``ActionType.NOOP`` on these samples so the policy gets positive
    gradient on the NOOP class across the obs distribution; without
    it, BC's cross-entropy over OPEN_BACK targets softmax-decays NOOP
    (and every other action class) to zero, which is what destroys
    close behaviour observed in round 3.
    """

    tick_index: int        # global pre-race tick index across the day
    runner_idx: int        # runner slot (env's sorted-sid index)
    obs: np.ndarray        # float32, shape (shim.obs_dim,)


# BC label augmentation Phase B (plans/bc-label-augmentation/). Target
# action class encoding for CloseHoldSample. Stored as int8 in the .npz
# (0=CLOSE, 1=NOOP/HOLD) — the discrete-action ActionType enum is
# resolved at BC time so the cache doesn't bind to a particular
# action-space layout.
TARGET_CLASS_CLOSE: int = 0
TARGET_CLASS_HOLD: int = 1


@dataclass(slots=True)
class CloseHoldSample:
    """One synthetic close-or-hold decision moment.

    BC label augmentation Phase B. Generated by forward-walking each
    oracle-positive open opportunity ``(T_open, R)`` and asking: would
    the hypothetical passive lay leg fill naturally before T-force-
    close, or would the env force-close the pair? Each pair contributes
    a handful of (T_close, R) samples where the obs is synthesised
    with non-zero position dims for runner R as if the agent had
    opened at T_open.

    ``target_action_class`` is one of:
      - :data:`TARGET_CLASS_CLOSE` (0): the pair force-closes → BC
        target is ``ActionType.CLOSE`` on slot ``runner_idx``.
      - :data:`TARGET_CLASS_HOLD` (1): the pair matures naturally →
        BC target is ``ActionType.NOOP`` (slot-less).

    ``lifecycle_position`` ∈ [0, 1] is the relative tick position
    along the pair's life from open to close; ``0.0`` = at-open,
    ``1.0`` = at force-close-deadline. Useful for downstream weight
    tuning if the close-too-early failure mode appears in
    validation.
    """

    tick_index: int            # global pre-race tick at T_close
    runner_idx: int            # runner slot
    obs: np.ndarray            # float32, shape (shim.obs_dim,)
    target_action_class: int   # 0=CLOSE, 1=HOLD/NOOP
    lifecycle_position: float  # [0.0, 1.0]


# ── Public API ───────────────────────────────────────────────────────────────


def _build_forward_walk_arrays(race):
    """Per-pre-race-tick arrays for the env-faithful passive-fill walk.

    Indexed by LOCAL pre-race tick index (0-based, in-play ticks
    excluded) — the ordering :func:`scan_day` walks. Captures exactly
    the per-tick state ``PassiveOrderBook.on_tick`` (volume mode) reads
    to decide a lay fill:
      - ``ttoff`` — time_to_off (s), for the T-fc cutoff;
      - ``ltp_by_sid`` — LTP (crossability gate + junk filter);
      - ``atl_by_sid`` — available-to-lay as ``(price, size)`` tuples
        (crossing latch + queue_ahead at placement);
      - ``tm_by_sid`` — per-runner ``total_matched`` (volume baseline).
    """
    ttoff: list[float] = []
    ltp_by_sid: list[dict] = []
    atl_by_sid: list[dict] = []
    tm_by_sid: list[dict] = []
    for tick in race.ticks:
        if tick.in_play:
            continue
        lmap: dict[int, float] = {}
        amap: dict[int, list] = {}
        tmap: dict[int, float] = {}
        for r in tick.runners:
            ltp = r.last_traded_price
            if ltp and ltp > 0:
                lmap[r.selection_id] = float(ltp)
            amap[r.selection_id] = [
                (lv.price, lv.size) for lv in r.available_to_lay
            ]
            tmap[r.selection_id] = float(
                getattr(r, "total_matched", 0.0) or 0.0
            )
        ltp_by_sid.append(lmap)
        atl_by_sid.append(amap)
        tm_by_sid.append(tmap)
        ttoff.append(
            (race.market_start_time - tick.timestamp).total_seconds()
        )
    return ttoff, ltp_by_sid, atl_by_sid, tm_by_sid


def _passive_lay_fills_before_fc(
    *,
    sid: int,
    lay_target: float,
    t_open_local: int,
    walk,
    fc_threshold: float,
    max_dev_pct: float = _DEFAULT_MAX_DEV_PCT,
) -> bool:
    """Env-faithful (volume mode) forward-walk: does a LONE resting passive
    lay at ``lay_target`` actually fill before the T-fc force-close?

    Replicates ``PassiveOrderBook.on_tick`` (env/bet_manager.py) for a
    single paired / explicit-price lay leg. A fill needs BOTH:

      1. the **crossing latch** — at some junk-passing tick the runner's
         ``available_to_lay`` has a level (size>0) priced ``<= P`` (a back
         offer has reached the resting limit); the latch is persistent;
      2. **cumulative traded volume >= queue_ahead** — where
         ``queue_ahead`` is the ATL size resting at exactly ``P`` at the
         open tick (0 if first in queue), and traded volume accumulates
         the per-runner ``total_matched`` delta only on ticks whose
         ``LTP <= P`` (the lay crossability gate, env ``_volume_phase_1``).

    NOTE: the earlier ATB-quote-touch heuristic (the close/hold
    augmentation) over-counted fills ~12x vs the env on holdout
    (63% vs 5%); it checked the wrong ladder (ATB not ATL) and ignored
    the queue/volume threshold entirely. See
    ``plans/imitation-first/findings.md`` Step 0.5 (2026-05-30).

    ``already_filled`` (passive self-depletion) is 0 by construction —
    we evaluate each candidate as a lone order, which is the right
    "would THIS open mature if placed alone?" labeling question.
    """
    ttoff, ltp_by_sid, atl_by_sid, tm_by_sid = walk
    n = len(ttoff)
    t_fc: int | None = None
    for j in range(t_open_local + 1, n):
        if ttoff[j] <= fc_threshold:
            t_fc = j
            break
    if t_fc is None:
        t_fc = n - 1
    if t_fc <= t_open_local:
        return False

    P = lay_target
    # queue_ahead = ATL size resting at exactly P at the open tick.
    queue_ahead = 0.0
    for price, size in atl_by_sid[t_open_local].get(sid, ()):  # noqa: E501
        if price > 0.0 and size > 0.0 and abs(price - P) < 1e-9:
            queue_ahead = size
            break

    prev_tm = tm_by_sid[t_open_local].get(sid)
    crossed = False
    cum_vol = 0.0
    for j in range(t_open_local + 1, t_fc + 1):
        cur_tm = tm_by_sid[j].get(sid)
        ltp = ltp_by_sid[j].get(sid, 0.0)
        # Phase 1: volume accumulation. Baseline updates every tick; the
        # delta is added only when the trade could cross a lay at P
        # (LTP <= P), matching env ``_volume_phase_1``.
        if prev_tm is not None and cur_tm is not None:
            delta = cur_tm - prev_tm
            if delta < 0.0:
                delta = 0.0
        else:
            delta = 0.0
        if cur_tm is not None:
            prev_tm = cur_tm
        if delta > 0.0 and 0.0 < ltp <= P:
            cum_vol += delta
        # Phase 2: junk filter -> crossing latch -> fill check.
        if ltp <= 0.0:
            continue
        lo = ltp * (1.0 - max_dev_pct)
        hi = ltp * (1.0 + max_dev_pct)
        if not (lo <= P <= hi):
            continue
        if not crossed:
            tops = [
                pr for pr, sz in atl_by_sid[j].get(sid, ())
                if pr > 0.0 and sz > 0.0
            ]
            if tops and min(tops) <= P + 1e-9:
                crossed = True
            if not crossed:
                continue
        if cum_vol >= queue_ahead:
            return True
    return False


def scan_day(
    date: str,
    data_dir: Path,
    config: dict,
    scorer_dir: Path = DEFAULT_SCORER_DIR,
    *,
    predictor_lean_obs: bool = False,
    predictor_bundle: object | None = None,
    use_race_outcome_predictor: bool = False,
    use_direction_predictor: bool = False,
    maturation_conditioned: bool = False,
    force_close_before_off_seconds: float = 120.0,
    maturation_label_out: dict | None = None,
) -> list[OracleSample]:
    """Scan one day; return samples for every profitable reachable arb moment.

    Only pre-race ticks emit samples (in-play ticks never allow bet
    placement). The shim's rolling-window ``FeatureExtractor`` is fed
    every tick (in-play included) so velocity features are correct on
    the pre-race ticks immediately following an in-play burst.

    2026-05-24: optionally inject the race-outcome + direction
    predictor outputs into the obs vector at scan time. Required when
    the downstream cohort uses ``--use-direction-predictor`` —
    otherwise the cache's 12 ``dir_*`` obs columns are zero-filled
    placeholders and downstream diagnostics that read them (e.g.
    ``tools/direction_signal_probe.py``) see only zeros.

    Samples are returned sorted by ``(tick_index, runner_idx)`` for
    determinism.
    """
    from data.episode_builder import load_day

    day = load_day(date, data_dir)
    if not day.races:
        return []

    env_kwargs = dict(
        scalping_mode=True,
        predictor_lean_obs=predictor_lean_obs,
    )
    if predictor_bundle is not None:
        env_kwargs["predictor_bundle"] = predictor_bundle
    if use_race_outcome_predictor:
        env_kwargs["use_race_outcome_predictor"] = True
    if use_direction_predictor:
        env_kwargs["use_direction_predictor"] = True
    env = BetfairEnv(day, config, **env_kwargs)
    shim = DiscreteActionShim(env, scorer_dir=scorer_dir)
    max_runners: int = env.max_runners

    commission: float = config.get("reward", {}).get("commission", 0.05)
    betting = config.get("training", {}).get("betting_constraints", {})
    max_back_price: float | None = betting.get("max_back_price")
    max_lay_price: float | None = betting.get("max_lay_price")
    starting_budget: float = float(
        config.get("training", {}).get("starting_budget", 100.0)
    )

    # Zero agent state for a fresh agent at any pre-race tick — same
    # construction as v1: in_play=0, budget_frac=1.0, liability=0,
    # race_bets=0, races_completed=0, day_pnl=0, (scalping) locked=0,
    # naked=0.
    agent_state_dim = AGENT_STATE_DIM + SCALPING_AGENT_STATE_DIM
    position_dim = max_runners * (POSITION_DIM + SCALPING_POSITION_DIM)
    zero_agent_state = np.zeros(agent_state_dim, dtype=np.float32)
    zero_agent_state[1] = 1.0  # budget_frac = 1.0
    zero_position = np.zeros(position_dim, dtype=np.float32)

    samples: list[OracleSample] = []
    global_tick = 0  # counts pre-race ticks only

    for race_idx, race in enumerate(day.races):
        env._race_idx = race_idx
        # Drop cross-race rolling-window state. Mirrors what the shim
        # does on ``reset`` between episodes.
        shim._feature_extractor = FeatureExtractor()
        runner_map = env._runner_maps[race_idx]

        # Maturation-conditioning (Step 0.5, plans/imitation-first):
        # precompute this race's per-pre-race-tick forward-walk arrays so
        # each candidate open can be gated on whether its passive lay
        # actually fills before T-fc. ``local_pre_idx`` indexes into them
        # (0-based over pre-race ticks, in lockstep with global_tick but
        # reset per race). None / unused when the flag is off.
        mc_walk = (
            _build_forward_walk_arrays(race)
            if (maturation_conditioned or maturation_label_out is not None)
            else None
        )
        local_pre_idx = -1

        for tick_idx, tick in enumerate(race.ticks):
            env._tick_idx = tick_idx
            # Update rolling-window state for EVERY tick (in_play
            # included) so velocity features on the next pre-race tick
            # remain correct after an in-play burst. The shim does the
            # same during a live rollout — every step's post-step
            # update sees the new tick before the next obs is built.
            shim._update_history_for_current_tick()

            if tick.in_play:
                continue
            local_pre_idx += 1

            # Build base obs (env's portion) the same way v1 does, then
            # let the shim append scorer features.
            static = env._static_obs[race_idx][tick_idx]
            base_obs = np.concatenate(
                [static, zero_agent_state, zero_position]
            )
            obs = shim.compute_extended_obs(base_obs)

            for runner in tick.runners:
                sid = runner.selection_id
                ltp = runner.last_traded_price
                if not ltp or ltp <= 0.0:
                    continue

                # ── Step 1: best available-to-back price after junk filter ──
                valid_atb = [
                    lv for lv in runner.available_to_back
                    if lv.size > 0.0
                    and passes_junk_filter(lv.price, ltp, _DEFAULT_MAX_DEV_PCT)
                ]
                if not valid_atb:
                    continue
                back_price = max(lv.price for lv in valid_atb)

                # ── Step 2: back price cap ───────────────────────────────────
                if not passes_price_cap(back_price, max_back_price):
                    continue

                # ── Step 3: minimum profitable tick spread ───────────────────
                min_ticks = min_arb_ticks_for_profit(
                    back_price, "back", commission,
                    max_ticks=MAX_ARB_TICKS,
                )
                if min_ticks is None:
                    continue

                # ── Step 4: passive lay price ────────────────────────────────
                lay_price = tick_offset(back_price, min_ticks, -1)
                if lay_price <= 0.0:
                    continue

                # ── Step 5: passive lay junk filter ─────────────────────────
                if not passes_junk_filter(lay_price, ltp, _DEFAULT_MAX_DEV_PCT):
                    continue

                # ── Step 6: lay price cap ────────────────────────────────────
                if not passes_price_cap(lay_price, max_lay_price):
                    continue

                # ── Step 7: freed-budget reservation check ───────────────────
                joint_factor = max(1.0, lay_price - 1.0)
                if starting_budget / joint_factor < _MIN_STAKE:
                    continue

                # ── Step 8: confirmed profitable ─────────────────────────────
                # The oracle scans back-first scalps (agg back, passive lay).
                # Equal-profit sizing matters here: a leg labelled
                # "profitable" must remain profitable under the env's
                # actual placement formula, not the legacy equal-exposure
                # form. See plans/force_close_and_arb_spread/ 2026-05-23.
                expected_locked_pnl = locked_pnl_per_unit_stake(
                    back_price, lay_price, commission,
                    aggressive_side="back",
                )
                if expected_locked_pnl <= 0.0:
                    continue

                runner_slot = runner_map.get(sid)
                if runner_slot is None:
                    continue

                # Maturation gate (Step 0.5): emit the OPEN label ONLY if
                # the passive lay would actually fill before T-fc on the
                # real future price path. Drops "spread placeable but
                # never matures" labels — Step 0 found ~89% of the
                # un-gated labels force-close on holdout. The forward-walk
                # is run once and reused for both the optional per-
                # candidate label dump (``maturation_label_out``, Step 1
                # predictability probe) and the filter.
                if mc_walk is not None:
                    _matured = _passive_lay_fills_before_fc(
                        sid=sid,
                        lay_target=lay_price,
                        t_open_local=local_pre_idx,
                        walk=mc_walk,
                        fc_threshold=float(force_close_before_off_seconds),
                    )
                    if maturation_label_out is not None:
                        maturation_label_out[
                            (global_tick, runner_slot)
                        ] = bool(_matured)
                    if maturation_conditioned and not _matured:
                        continue

                samples.append(OracleSample(
                    tick_index=global_tick,
                    runner_idx=runner_slot,
                    obs=obs.copy(),
                    arb_spread_ticks=min_ticks,
                    expected_locked_pnl=float(expected_locked_pnl),
                ))

            global_tick += 1

    samples.sort(key=lambda s: (s.tick_index, s.runner_idx))
    return samples


def scan_day_negative(
    date: str,
    data_dir: Path,
    config: dict,
    positive_samples: list[OracleSample],
    scorer_dir: Path = DEFAULT_SCORER_DIR,
    *,
    predictor_lean_obs: bool = False,
    predictor_bundle: object | None = None,
    use_race_outcome_predictor: bool = False,
    use_direction_predictor: bool = False,
    negative_ratio: float = 2.0,
    seed: int = 0,
) -> list[NegativeOracleSample]:
    """Walk the same pre-race ticks and emit negative-open samples.

    BC label augmentation Phase A. A "negative" sample is a (tick,
    runner_idx) pair whose obs has the same construction as a positive
    sample at that (tick, runner) but where NO profitable arb exists.
    Subsampled at ``negative_ratio`` × len(positive_samples) (default
    2× positives) — the BC pool then becomes ~3 samples total per
    positive (1 OPEN_BACK + 2 NOOP), which puts positive gradient on
    NOOP without overwhelming the open signal.

    The walk and obs construction mirror :func:`scan_day` exactly so
    the negative-pool obs is byte-comparable to a positive at the
    same (tick, runner). Determinism: same date + same config +
    same positive set + same seed → byte-identical negatives.

    The positive set is consumed as a guard: any (tick, runner) that
    is already in ``positive_samples`` is skipped (cannot appear in
    both pools).
    """
    from data.episode_builder import load_day

    day = load_day(date, data_dir)
    if not day.races:
        return []

    pos_keys: set[tuple[int, int]] = {
        (s.tick_index, s.runner_idx) for s in positive_samples
    }
    target_count = max(0, int(len(positive_samples) * float(negative_ratio)))
    if target_count <= 0:
        return []

    env_kwargs = dict(
        scalping_mode=True,
        predictor_lean_obs=predictor_lean_obs,
    )
    if predictor_bundle is not None:
        env_kwargs["predictor_bundle"] = predictor_bundle
    if use_race_outcome_predictor:
        env_kwargs["use_race_outcome_predictor"] = True
    if use_direction_predictor:
        env_kwargs["use_direction_predictor"] = True
    env = BetfairEnv(day, config, **env_kwargs)
    shim = DiscreteActionShim(env, scorer_dir=scorer_dir)
    max_runners: int = env.max_runners

    # Mirror scan_day's zero state construction exactly.
    agent_state_dim = AGENT_STATE_DIM + SCALPING_AGENT_STATE_DIM
    position_dim = max_runners * (POSITION_DIM + SCALPING_POSITION_DIM)
    zero_agent_state = np.zeros(agent_state_dim, dtype=np.float32)
    zero_agent_state[1] = 1.0
    zero_position = np.zeros(position_dim, dtype=np.float32)

    # First pass: enumerate candidate (tick_index, runner_idx, obs)
    # triples in deterministic order. We materialise obs vectors here
    # so reservoir-sampling later doesn't have to walk twice.
    candidates: list[NegativeOracleSample] = []
    global_tick = 0

    for race_idx, race in enumerate(day.races):
        env._race_idx = race_idx
        shim._feature_extractor = FeatureExtractor()
        runner_map = env._runner_maps[race_idx]

        for tick_idx, tick in enumerate(race.ticks):
            env._tick_idx = tick_idx
            shim._update_history_for_current_tick()

            if tick.in_play:
                continue

            static = env._static_obs[race_idx][tick_idx]
            base_obs = np.concatenate(
                [static, zero_agent_state, zero_position]
            )
            obs = shim.compute_extended_obs(base_obs)

            # Build the set of runner slots present in this tick. A
            # negative needs a present-and-active runner — otherwise
            # the obs's position dim is meaningless and BC would
            # learn NOOP on garbage. Mirror the positive scan's
            # filtering (LTP > 0) so the obs distribution matches.
            for runner in tick.runners:
                sid = runner.selection_id
                ltp = runner.last_traded_price
                if not ltp or ltp <= 0.0:
                    continue
                runner_slot = runner_map.get(sid)
                if runner_slot is None:
                    continue
                key = (global_tick, runner_slot)
                if key in pos_keys:
                    continue
                candidates.append(NegativeOracleSample(
                    tick_index=global_tick,
                    runner_idx=runner_slot,
                    obs=obs.copy(),
                ))

            global_tick += 1

    if not candidates:
        return []

    # Reservoir-style subsample to ``target_count`` for determinism +
    # to keep the pool bounded. Use a numpy RNG seeded by the input
    # seed so two scans of the same day produce byte-identical output.
    if len(candidates) <= target_count:
        chosen = candidates
    else:
        rng = np.random.default_rng(int(seed))
        idx = rng.choice(
            len(candidates), size=target_count, replace=False,
        )
        idx.sort()
        chosen = [candidates[int(i)] for i in idx]

    chosen.sort(key=lambda s: (s.tick_index, s.runner_idx))
    return chosen


def save_samples(
    samples: list[OracleSample],
    date: str,
    data_dir: Path,
    config: dict,
    total_ticks: int,
    obs_dim: int,
) -> Path:
    """Write cache to ``data/oracle_cache_v2/{date}/``.

    Returns the path of the written ``.npz`` file. Cache directory is
    distinct from v1's ``oracle_cache/`` so the two stacks can coexist.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    cache_dir.mkdir(parents=True, exist_ok=True)
    out_path = cache_dir / "oracle_samples.npz"

    header = {
        "obs_schema_version": OBS_SCHEMA_VERSION,
        "action_schema_version": ACTION_SCHEMA_VERSION,
        "scalping_mode": True,
        "v2_extended_obs": True,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "commit_sha": _git_sha(),
        "samples": len(samples),
        "ticks": total_ticks,
        "density": len(samples) / max(total_ticks, 1),
        "unique_arb_ticks": len({s.tick_index for s in samples}),
        "unique_arb_ticks_density": (
            len({s.tick_index for s in samples}) / max(total_ticks, 1)
        ),
        "obs_dim": obs_dim,
    }
    (cache_dir / "header.json").write_text(
        json.dumps(header, indent=2), encoding="utf-8"
    )

    _save_samples_atomic(samples, out_path, obs_dim)
    return out_path


def load_samples(
    date: str,
    data_dir: Path,
    *,
    strict: bool = True,
    expected_obs_dim: int | None = None,
) -> list[OracleSample]:
    """Load cached samples from ``data/oracle_cache_v2/{date}/oracle_samples.npz``.

    Parameters
    ----------
    strict:
        When ``True`` (default), assert that stored schema versions
        match the current env. If ``expected_obs_dim`` is also given,
        the stored ``obs_dim`` must match it too — guards the v2 stack
        against silently loading a v1 cache or a cache produced under a
        different ``max_runners``.
    expected_obs_dim:
        Optional. Set by ``DiscretePPOTrainer`` to ``shim.obs_dim`` so
        a stale cache with the wrong scorer-feature width is rejected
        rather than fed into BC and producing garbage gradients.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    npz_path = cache_dir / "oracle_samples.npz"
    if not npz_path.exists():
        raise FileNotFoundError(f"Oracle cache not found: {npz_path}")

    data = np.load(npz_path, allow_pickle=False)

    if strict:
        saved_obs = int(data["obs_schema_version"])
        saved_act = int(data["action_schema_version"])
        if saved_obs != OBS_SCHEMA_VERSION:
            raise ValueError(
                f"Cache obs_schema_version={saved_obs} but env expects "
                f"OBS_SCHEMA_VERSION={OBS_SCHEMA_VERSION}. Re-run oracle scan."
            )
        if saved_act != ACTION_SCHEMA_VERSION:
            raise ValueError(
                f"Cache action_schema_version={saved_act} but env expects "
                f"ACTION_SCHEMA_VERSION={ACTION_SCHEMA_VERSION}. "
                "Re-run oracle scan."
            )
        if expected_obs_dim is not None:
            saved_dim = int(data["obs_dim_stored"])
            if saved_dim != int(expected_obs_dim):
                raise ValueError(
                    f"Cache obs_dim={saved_dim} but caller expects "
                    f"{expected_obs_dim}. Re-run oracle scan against the "
                    "current shim/scorer configuration."
                )

    tick_arr = data["tick_index"]
    runner_arr = data["runner_idx"]
    obs_matrix = data["obs"]
    spread_arr = data["arb_spread_ticks"]
    pnl_arr = data["expected_locked_pnl"]

    return [
        OracleSample(
            tick_index=int(tick_arr[i]),
            runner_idx=int(runner_arr[i]),
            obs=obs_matrix[i].astype(np.float32),
            arb_spread_ticks=int(spread_arr[i]),
            expected_locked_pnl=float(pnl_arr[i]),
        )
        for i in range(len(tick_arr))
    ]


def save_negative_samples(
    samples: list[NegativeOracleSample],
    date: str,
    data_dir: Path,
    config: dict,
    total_ticks: int,
    obs_dim: int,
) -> Path:
    """Write the negative-pool cache to
    ``data/oracle_cache_v2/{date}/oracle_samples_negative.npz``.

    BC label augmentation Phase A. Sibling of :func:`save_samples`;
    does NOT touch the positive cache. Returns the path of the
    written ``.npz`` file.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    cache_dir.mkdir(parents=True, exist_ok=True)
    out_path = cache_dir / "oracle_samples_negative.npz"

    header = {
        "obs_schema_version": OBS_SCHEMA_VERSION,
        "action_schema_version": ACTION_SCHEMA_VERSION,
        "scalping_mode": True,
        "v2_extended_obs": True,
        "kind": "negative",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "commit_sha": _git_sha(),
        "samples": len(samples),
        "ticks": total_ticks,
        "density": len(samples) / max(total_ticks, 1),
        "obs_dim": obs_dim,
    }
    (cache_dir / "header_negative.json").write_text(
        json.dumps(header, indent=2), encoding="utf-8"
    )

    _save_negative_samples_atomic(samples, out_path, obs_dim)
    return out_path


def load_negative_samples(
    date: str,
    data_dir: Path,
    *,
    strict: bool = True,
    expected_obs_dim: int | None = None,
) -> list[NegativeOracleSample]:
    """Load the negative-pool cache from
    ``data/oracle_cache_v2/{date}/oracle_samples_negative.npz``.

    Returns an EMPTY LIST when the cache file is missing (does NOT
    raise) — BC label augmentation Phase A degrades gracefully so
    downstream BC code can pass ``--bc-include-negative-samples``
    against a cache that hasn't yet been re-scanned. A warning is
    logged on the missing-cache path.

    Parameters mirror :func:`load_samples` precisely; ``strict`` and
    ``expected_obs_dim`` semantics are identical.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    npz_path = cache_dir / "oracle_samples_negative.npz"
    if not npz_path.exists():
        logger.warning(
            "Negative oracle cache missing for %s at %s; returning "
            "empty list. Re-run `python -m training_v2.oracle_cli "
            "scan --include-negative-samples --dates %s` to populate.",
            date, npz_path, date,
        )
        return []

    data = np.load(npz_path, allow_pickle=False)

    if strict:
        saved_obs = int(data["obs_schema_version"])
        saved_act = int(data["action_schema_version"])
        if saved_obs != OBS_SCHEMA_VERSION:
            raise ValueError(
                f"Negative cache obs_schema_version={saved_obs} but env "
                f"expects OBS_SCHEMA_VERSION={OBS_SCHEMA_VERSION}. "
                "Re-run oracle scan."
            )
        if saved_act != ACTION_SCHEMA_VERSION:
            raise ValueError(
                f"Negative cache action_schema_version={saved_act} but "
                f"env expects ACTION_SCHEMA_VERSION={ACTION_SCHEMA_VERSION}"
                ". Re-run oracle scan."
            )
        if expected_obs_dim is not None:
            saved_dim = int(data["obs_dim_stored"])
            if saved_dim != int(expected_obs_dim):
                raise ValueError(
                    f"Negative cache obs_dim={saved_dim} but caller "
                    f"expects {expected_obs_dim}. Re-run oracle scan "
                    "against the current shim/scorer configuration."
                )

    tick_arr = data["tick_index"]
    runner_arr = data["runner_idx"]
    obs_matrix = data["obs"]

    return [
        NegativeOracleSample(
            tick_index=int(tick_arr[i]),
            runner_idx=int(runner_arr[i]),
            obs=obs_matrix[i].astype(np.float32),
        )
        for i in range(len(tick_arr))
    ]


def scan_day_close_hold(
    date: str,
    data_dir: Path,
    config: dict,
    scorer_dir: Path = DEFAULT_SCORER_DIR,
    *,
    predictor_lean_obs: bool = False,
    predictor_bundle: object | None = None,
    use_race_outcome_predictor: bool = False,
    use_direction_predictor: bool = False,
    force_close_before_off_seconds: float = 120.0,
    max_samples_per_pair: int = 5,
    seed: int = 0,
) -> list["CloseHoldSample"]:
    """Walk pre-race ticks; for each oracle-positive open, forward-walk
    runner R's ladder to decide whether the hypothetical passive lay
    would fill naturally (HOLD/NOOP target) or be force-closed at
    T-off ``force_close_before_off_seconds`` (CLOSE target).

    BC label augmentation Phase B (``plans/bc-label-augmentation/``).
    For each positive open ``(T_open, R)``:

    1. Compute the hypothetical passive lay price using the same
       ``min_arb_ticks_for_profit`` floor the env applies on open.
    2. Forward-walk from ``T_open + 1`` to the first pre-race tick
       whose ``time_to_off`` is at or below
       ``force_close_before_off_seconds``. The pair "matures
       naturally" iff there is a tick during this window where
       runner R's ``available_to_back`` ladder has a level whose
       price <= ``lay_target`` with non-zero size AND that level
       passes the junk filter against the LTP at that tick. (When
       the agent is resting a passive lay at price L, fills come
       from the opposite-side aggressors crossing in — i.e. ATB
       quotes priced <= L.)
    3. Pair lifecycle ticks are ``(T_open, T_close]`` where
       ``T_close`` is the natural-fill tick (HOLD outcome) or the
       force-close tick (CLOSE outcome). At most
       ``max_samples_per_pair`` lifecycle ticks contribute samples:
       start, near-mid, two near-end, and one random (deterministic
       via ``seed``). Caps the pool size — we can tune later.
    4. At each selected ``(T_close, R)``, synthesise an obs:
       - Same base construction as :func:`scan_day` but the
         per-runner position slice for slot R is populated as if
         the agent had matched the aggressive back leg at
         ``back_price`` (at T_open) and placed a partner passive
         lay at ``lay_target``. We populate the subset of position
         dims that encode "agent has an open pair on this runner"
         — back_exposure, bet_count, has_arb, proximity,
         seconds_since, price_delta, agg_age. Other dims (lay
         exposure, naked-leverage cluster) stay zero since by
         construction the pair has only ONE matched leg and the
         partner is in the passive book (not naked).

    Returns samples sorted by ``(tick_index, runner_idx)`` for
    determinism. Same date + same config + same seed → byte-identical
    output (same contract as :func:`scan_day`).
    """
    from data.episode_builder import load_day

    day = load_day(date, data_dir)
    if not day.races:
        return []

    env_kwargs = dict(
        scalping_mode=True,
        predictor_lean_obs=predictor_lean_obs,
    )
    if predictor_bundle is not None:
        env_kwargs["predictor_bundle"] = predictor_bundle
    if use_race_outcome_predictor:
        env_kwargs["use_race_outcome_predictor"] = True
    if use_direction_predictor:
        env_kwargs["use_direction_predictor"] = True
    env = BetfairEnv(day, config, **env_kwargs)
    shim = DiscreteActionShim(env, scorer_dir=scorer_dir)
    max_runners: int = env.max_runners

    commission: float = config.get("reward", {}).get("commission", 0.05)
    betting = config.get("training", {}).get("betting_constraints", {})
    max_back_price: float | None = betting.get("max_back_price")
    max_lay_price: float | None = betting.get("max_lay_price")
    starting_budget: float = float(
        config.get("training", {}).get("starting_budget", 100.0)
    )
    max_bets: int = max(int(config.get("training", {}).get(
        "max_bets_per_race", 20,
    )), 1)
    fc_threshold = float(force_close_before_off_seconds)

    agent_state_dim = AGENT_STATE_DIM + SCALPING_AGENT_STATE_DIM
    per_runner_pos = POSITION_DIM + SCALPING_POSITION_DIM
    position_dim = max_runners * per_runner_pos
    max_arb_ticks_local = max(MAX_ARB_TICKS, 1)

    samples: list[CloseHoldSample] = []
    rng = np.random.default_rng(int(seed))

    # global pre-race tick counter (mirrors scan_day's global_tick)
    global_tick_base_by_race: list[int] = []  # global tick of race[i]'s tick 0
    running = 0
    for race in day.races:
        global_tick_base_by_race.append(running)
        # count this race's pre-race ticks but we'll re-walk later
        running += sum(1 for tick in race.ticks if not tick.in_play)
    # Note: scan_day's global_tick is over pre-race ticks only; we
    # mirror exactly. Build per-race lists of (local_pre_race_idx,
    # tick_local_idx) so we can index by local_pre_race_idx.

    for race_idx, race in enumerate(day.races):
        env._race_idx = race_idx
        shim._feature_extractor = FeatureExtractor()
        runner_map = env._runner_maps[race_idx]
        race_duration = env._race_durations[race_idx]
        race_duration_safe = max(float(race_duration), 1.0)

        # Pre-race tick indices in this race (local), in order.
        pre_race_local_idx: list[int] = [
            i for i, t in enumerate(race.ticks) if not t.in_play
        ]
        # Per-pre-race-tick LTP/time-to-off for the forward walk.
        per_tick_ltp_by_sid: list[dict[int, float]] = []
        per_tick_time_to_off: list[float] = []
        per_tick_atb_by_sid: list[dict[int, list]] = []
        per_tick_global_idx: list[int] = []  # global pre-race tick number
        race_base = global_tick_base_by_race[race_idx]
        for local_pre_idx, tick_local in enumerate(pre_race_local_idx):
            tick = race.ticks[tick_local]
            ltp_map: dict[int, float] = {}
            atb_map: dict[int, list] = {}
            for r in tick.runners:
                if r.last_traded_price and r.last_traded_price > 0:
                    ltp_map[r.selection_id] = float(r.last_traded_price)
                atb_map[r.selection_id] = list(r.available_to_back)
            per_tick_ltp_by_sid.append(ltp_map)
            per_tick_atb_by_sid.append(atb_map)
            t_to_off = (
                race.market_start_time - tick.timestamp
            ).total_seconds()
            per_tick_time_to_off.append(float(t_to_off))
            per_tick_global_idx.append(race_base + local_pre_idx)

        # Walk every tick of the race in order so the shim's rolling
        # window stays correct on pre-race ticks. For each pre-race
        # tick, scan for oracle-positive opens; for each, forward-walk
        # the *local pre-race* sequence to decide CLOSE vs HOLD.
        local_pre_idx_walker = 0
        for tick_idx, tick in enumerate(race.ticks):
            env._tick_idx = tick_idx
            shim._update_history_for_current_tick()

            if tick.in_play:
                continue

            # Determine the local pre-race idx for this tick.
            local_pre_idx = local_pre_idx_walker
            local_pre_idx_walker += 1

            # Skip if past the force-close threshold (no time to
            # synthesise meaningful close/hold lifecycle).
            t_to_off_here = per_tick_time_to_off[local_pre_idx]
            if t_to_off_here <= fc_threshold:
                continue

            # Build the static base obs at this tick — needed only
            # if we end up emitting samples here (otherwise wasted
            # work). Cache lazily.
            base_static = None

            for runner in tick.runners:
                sid = runner.selection_id
                ltp = runner.last_traded_price
                if not ltp or ltp <= 0.0:
                    continue
                valid_atb = [
                    lv for lv in runner.available_to_back
                    if lv.size > 0.0
                    and passes_junk_filter(lv.price, ltp, _DEFAULT_MAX_DEV_PCT)
                ]
                if not valid_atb:
                    continue
                back_price = max(lv.price for lv in valid_atb)
                if not passes_price_cap(back_price, max_back_price):
                    continue
                min_ticks = min_arb_ticks_for_profit(
                    back_price, "back", commission,
                    max_ticks=MAX_ARB_TICKS,
                )
                if min_ticks is None:
                    continue
                lay_target = tick_offset(back_price, min_ticks, -1)
                if lay_target <= 0.0:
                    continue
                if not passes_junk_filter(
                    lay_target, ltp, _DEFAULT_MAX_DEV_PCT,
                ):
                    continue
                if not passes_price_cap(lay_target, max_lay_price):
                    continue
                joint_factor = max(1.0, lay_target - 1.0)
                if starting_budget / joint_factor < _MIN_STAKE:
                    continue
                expected_locked_pnl = locked_pnl_per_unit_stake(
                    back_price, lay_target, commission,
                    aggressive_side="back",
                )
                if expected_locked_pnl <= 0.0:
                    continue
                runner_slot = runner_map.get(sid)
                if runner_slot is None:
                    continue

                # ── Forward walk: does the passive lay fill before
                # T-fc_threshold? ──
                t_open_local = local_pre_idx
                # Find T_force_close_local: first pre-race tick whose
                # time_to_off <= fc_threshold (inclusive). If none,
                # use the last pre-race tick.
                t_fc_local = None
                for j in range(t_open_local + 1, len(per_tick_time_to_off)):
                    if per_tick_time_to_off[j] <= fc_threshold:
                        t_fc_local = j
                        break
                if t_fc_local is None:
                    t_fc_local = len(per_tick_time_to_off) - 1
                if t_fc_local <= t_open_local:
                    # No life-window — skip this open.
                    continue

                # Look for natural fill: any ATB price <= lay_target
                # (with size > 0 and passing junk filter against
                # that tick's LTP) anywhere in (T_open, T_fc].
                natural_fill_local: int | None = None
                for j in range(t_open_local + 1, t_fc_local + 1):
                    atb_levels = per_tick_atb_by_sid[j].get(sid) or []
                    fwd_ltp = per_tick_ltp_by_sid[j].get(sid, 0.0)
                    if fwd_ltp <= 0.0:
                        continue
                    for lv in atb_levels:
                        if lv.size <= 0.0:
                            continue
                        if lv.price > lay_target:
                            continue
                        if not passes_junk_filter(
                            lv.price, fwd_ltp, _DEFAULT_MAX_DEV_PCT,
                        ):
                            continue
                        natural_fill_local = j
                        break
                    if natural_fill_local is not None:
                        break

                if natural_fill_local is not None:
                    target_class = TARGET_CLASS_HOLD
                    t_close_local = natural_fill_local
                else:
                    target_class = TARGET_CLASS_CLOSE
                    t_close_local = t_fc_local

                life_span = t_close_local - t_open_local
                if life_span <= 0:
                    continue

                # Pick at most max_samples_per_pair lifecycle ticks:
                # start, near-mid, two near-end, one random.
                candidate_offsets: list[int] = []
                if life_span >= 1:
                    candidate_offsets.append(1)
                if life_span >= 3:
                    candidate_offsets.append(life_span // 2)
                if life_span >= 2:
                    candidate_offsets.append(max(1, life_span - 1))
                if life_span >= 4:
                    candidate_offsets.append(life_span)
                if life_span >= 2 and max_samples_per_pair >= 5:
                    # one deterministic random offset
                    rnd = int(rng.integers(1, life_span + 1))
                    candidate_offsets.append(rnd)
                # Dedup and cap
                seen: set[int] = set()
                offsets: list[int] = []
                for o in candidate_offsets:
                    if o < 1 or o > life_span:
                        continue
                    if o in seen:
                        continue
                    seen.add(o)
                    offsets.append(o)
                    if len(offsets) >= int(max_samples_per_pair):
                        break
                if not offsets:
                    continue

                # Static obs at T_open (the same construction as
                # scan_day) — for each sample, we recompute the base
                # static obs at T_close's tick (because static
                # features evolve per-tick). To keep this cheap, the
                # rolling window must already be primed at T_close —
                # but we're inside the T_open loop. Approach: for
                # each lifecycle offset, grab the static features
                # from env._static_obs[race_idx][tick_local] at the
                # T_close tick. Rolling-window scorer features
                # require the FeatureExtractor's state at T_close
                # which is only correct if we walk forward — but
                # for the Phase B synthesis we use the rolling-
                # window state captured AT T_OPEN. Pragmatic
                # tradeoff: the scorer features are stable across a
                # ~60s window (they roll slowly) and the position
                # dims are what carry the load-bearing signal for
                # the CLOSE label. Document in the docstring; if the
                # F2 validation shows this is insufficient we can
                # revisit with a second-pass walk.
                #
                # Build the rolling-extended obs at T_OPEN. Then for
                # each offset, swap the per-tick static_obs slice to
                # T_close's static_obs (env._static_obs lookup is
                # cheap). The shim's compute_extended_obs uses the
                # internal feature_extractor state; we pin to T_open
                # state by design.
                obs_open = shim.compute_extended_obs(
                    np.concatenate([
                        env._static_obs[race_idx][tick_idx],
                        np.zeros(agent_state_dim, dtype=np.float32),
                        np.zeros(position_dim, dtype=np.float32),
                    ])
                ).copy()
                # The shim appends 2 * max_runners floats after the
                # env-only obs. Compute that offset so we can swap
                # the env-only static slice per-tick while keeping
                # the shim columns from T_open.
                env_only_len = (
                    env.observation_space.shape[0]
                )
                # static_len is the per-tick precomputed feature
                # slice length stored in env._static_obs.
                static_len = env._static_obs[race_idx][tick_idx].shape[0]

                # Build the per-runner position vector ONCE for this
                # pair (re-used across lifecycle offsets — but we
                # rebuild proximity/seconds_since per offset).
                # Aggressive stake assumption: minimum stake at the
                # equal-profit pair size — but for the obs we only
                # need representative magnitudes. Use the per-pair
                # stake produced by the env's equal-profit formula
                # at min stake; since the obs normalises by budget,
                # back_exposure = (S * back_price) / budget.
                back_stake = float(_MIN_STAKE)
                # back_exposure: stake * (price - 1) is the liability
                # convention for a back? In env at line 2585 it reads
                # ``pos["back_exposure"] / budget`` — back_exposure
                # in BetManager is matched_stake * (price - 1) for
                # losses, but the obs normalisation just divides.
                # For the synthesis we use back_stake * (back_price-1)
                # to roughly mirror what positions.back_exposure
                # returns on a matched back leg.
                back_exposure_norm = (
                    back_stake * max(back_price - 1.0, 0.0)
                ) / max(starting_budget, 1.0)
                back_exposure_norm = float(min(back_exposure_norm, 1.0))

                # Common per-pair fields:
                placed_tto = per_tick_time_to_off[t_open_local]

                for offset in offsets:
                    t_close_offset_local = t_open_local + offset
                    t_close_offset_local = min(
                        t_close_offset_local, t_close_local,
                    )
                    t_close_tick_local = pre_race_local_idx[
                        t_close_offset_local
                    ]
                    # tick-time, ltp at T_close offset:
                    fwd_ltp = per_tick_ltp_by_sid[
                        t_close_offset_local
                    ].get(sid, 0.0)
                    current_tto = per_tick_time_to_off[
                        t_close_offset_local
                    ]
                    # Build the position vector for this offset.
                    pos_vec = np.zeros(position_dim, dtype=np.float32)
                    off = runner_slot * per_runner_pos
                    # back_exposure (POSITION_DIM[0])
                    pos_vec[off + 0] = back_exposure_norm
                    # lay_exposure (POSITION_DIM[1]) = 0
                    # bet_count (POSITION_DIM[2]) = 1 / max_bets
                    pos_vec[off + 2] = 1.0 / max_bets
                    # SCALPING per-runner block starts at off + POSITION_DIM
                    sc = off + POSITION_DIM
                    # has_arb = 1.0 (load-bearing binary)
                    pos_vec[sc + 0] = 1.0
                    # proximity / price_delta from passive resting
                    # at lay_target vs current LTP.
                    if fwd_ltp > 0.0:
                        unsigned_dist = ticks_between(fwd_ltp, lay_target)
                        proximity = 1.0 / (1.0 + unsigned_dist / 5.0)
                        signed_dist = (
                            unsigned_dist if lay_target > fwd_ltp
                            else -unsigned_dist
                        )
                        price_delta = float(np.clip(
                            signed_dist / max_arb_ticks_local,
                            -1.0, 1.0,
                        ))
                    else:
                        proximity = 0.0
                        price_delta = 0.0
                    pos_vec[sc + 1] = float(proximity)
                    elapsed = max(0.0, placed_tto - current_tto)
                    seconds_since = float(np.clip(
                        elapsed / race_duration_safe, 0.0, 1.0,
                    ))
                    pos_vec[sc + 2] = seconds_since
                    pos_vec[sc + 3] = price_delta
                    # naked dims (sc + 4..7) stay zero — the pair has
                    # a passive partner posted; it is NOT naked.
                    # agg_age (sc + 8) mirrors seconds_since (the
                    # aggressive leg was placed at the same tick).
                    pos_vec[sc + 8] = seconds_since

                    # Compose final obs: env-only obs at T_close
                    # (static + zero agent state + position vec) +
                    # shim's appended scorer columns from T_open.
                    new_env_only = np.concatenate([
                        env._static_obs[race_idx][t_close_tick_local],
                        np.zeros(agent_state_dim, dtype=np.float32),
                        pos_vec,
                    ]).astype(np.float32)
                    # Splice into obs_open: replace [0:env_only_len]
                    # with new_env_only; keep the shim's [env_only_len:]
                    # columns from T_open as a pragmatic approximation
                    # (see docstring).
                    obs_synth = obs_open.copy()
                    if new_env_only.shape[0] >= env_only_len:
                        obs_synth[:env_only_len] = (
                            new_env_only[:env_only_len]
                        )
                    else:
                        obs_synth[:new_env_only.shape[0]] = new_env_only

                    lifecycle_position = float(
                        offset / max(life_span, 1),
                    )
                    lifecycle_position = float(np.clip(
                        lifecycle_position, 0.0, 1.0,
                    ))

                    samples.append(CloseHoldSample(
                        tick_index=per_tick_global_idx[
                            t_close_offset_local
                        ],
                        runner_idx=runner_slot,
                        obs=obs_synth,
                        target_action_class=int(target_class),
                        lifecycle_position=lifecycle_position,
                    ))

    samples.sort(key=lambda s: (s.tick_index, s.runner_idx))
    return samples


def save_close_hold_samples(
    samples: list["CloseHoldSample"],
    date: str,
    data_dir: Path,
    config: dict,
    total_ticks: int,
    obs_dim: int,
) -> Path:
    """Write Phase B cache to
    ``data/oracle_cache_v2/{date}/oracle_samples_close_hold.npz``.

    BC label augmentation Phase B. Sibling of :func:`save_samples` and
    :func:`save_negative_samples`; does NOT touch either of those.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    cache_dir.mkdir(parents=True, exist_ok=True)
    out_path = cache_dir / "oracle_samples_close_hold.npz"

    n_close = sum(
        1 for s in samples if s.target_action_class == TARGET_CLASS_CLOSE
    )
    n_hold = sum(
        1 for s in samples if s.target_action_class == TARGET_CLASS_HOLD
    )
    header = {
        "obs_schema_version": OBS_SCHEMA_VERSION,
        "action_schema_version": ACTION_SCHEMA_VERSION,
        "scalping_mode": True,
        "v2_extended_obs": True,
        "kind": "close_hold",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "commit_sha": _git_sha(),
        "samples": len(samples),
        "close_samples": n_close,
        "hold_samples": n_hold,
        "ticks": total_ticks,
        "density": len(samples) / max(total_ticks, 1),
        "obs_dim": obs_dim,
    }
    (cache_dir / "header_close_hold.json").write_text(
        json.dumps(header, indent=2), encoding="utf-8"
    )

    _save_close_hold_samples_atomic(samples, out_path, obs_dim)
    return out_path


def load_close_hold_samples(
    date: str,
    data_dir: Path,
    *,
    strict: bool = True,
    expected_obs_dim: int | None = None,
) -> list["CloseHoldSample"]:
    """Load Phase B cache from
    ``data/oracle_cache_v2/{date}/oracle_samples_close_hold.npz``.

    Returns an EMPTY LIST when the cache file is missing (does NOT
    raise) — mirrors :func:`load_negative_samples` exactly. A warning
    is logged on the missing-cache path.
    """
    cache_dir = data_dir.parent / "oracle_cache_v2" / date
    npz_path = cache_dir / "oracle_samples_close_hold.npz"
    if not npz_path.exists():
        logger.warning(
            "Close/hold oracle cache missing for %s at %s; returning "
            "empty list. Re-run `python -m training_v2.oracle_cli "
            "scan --include-close-hold-samples --dates %s` to populate.",
            date, npz_path, date,
        )
        return []

    data = np.load(npz_path, allow_pickle=False)

    if strict:
        saved_obs = int(data["obs_schema_version"])
        saved_act = int(data["action_schema_version"])
        if saved_obs != OBS_SCHEMA_VERSION:
            raise ValueError(
                f"Close/hold cache obs_schema_version={saved_obs} but "
                f"env expects OBS_SCHEMA_VERSION={OBS_SCHEMA_VERSION}. "
                "Re-run oracle scan."
            )
        if saved_act != ACTION_SCHEMA_VERSION:
            raise ValueError(
                f"Close/hold cache action_schema_version={saved_act} "
                f"but env expects ACTION_SCHEMA_VERSION="
                f"{ACTION_SCHEMA_VERSION}. Re-run oracle scan."
            )
        if expected_obs_dim is not None:
            saved_dim = int(data["obs_dim_stored"])
            if saved_dim != int(expected_obs_dim):
                raise ValueError(
                    f"Close/hold cache obs_dim={saved_dim} but caller "
                    f"expects {expected_obs_dim}. Re-run oracle scan "
                    "against the current shim/scorer configuration."
                )

    tick_arr = data["tick_index"]
    runner_arr = data["runner_idx"]
    obs_matrix = data["obs"]
    target_arr = data["target_action_class"]
    lp_arr = data["lifecycle_position"]

    return [
        CloseHoldSample(
            tick_index=int(tick_arr[i]),
            runner_idx=int(runner_arr[i]),
            obs=obs_matrix[i].astype(np.float32),
            target_action_class=int(target_arr[i]),
            lifecycle_position=float(lp_arr[i]),
        )
        for i in range(len(tick_arr))
    ]


def count_pre_race_ticks(date: str, data_dir: Path) -> int:
    """Return the total number of pre-race ticks across all races for *date*."""
    from data.episode_builder import load_day
    try:
        day = load_day(date, data_dir)
    except FileNotFoundError:
        return 0
    return sum(
        1
        for race in day.races
        for tick in race.ticks
        if not tick.in_play
    )


# ── Internal helpers ─────────────────────────────────────────────────────────


def _save_samples_atomic(
    samples: list[OracleSample],
    path: Path,
    obs_dim: int,
) -> None:
    """Write .npz to a tmp file then rename for atomicity.

    Mirrors v1's atomic-write pattern (``training/arb_oracle.py``) — np.savez
    appends ``.npz`` to its target stem so we name the temp file with a
    ``_tmp`` stem and rename the produced ``_tmp.npz`` to *path* on success.
    """
    tmp_stem = path.parent / (path.stem + "_tmp")     # no extension
    tmp = path.parent / (path.stem + "_tmp.npz")      # what np.savez produces
    n = len(samples)

    if n > 0:
        obs_matrix = np.stack([s.obs for s in samples]).astype(np.float32)
        tick_arr = np.array([s.tick_index for s in samples], dtype=np.int32)
        runner_arr = np.array([s.runner_idx for s in samples], dtype=np.int32)
        spread_arr = np.array(
            [s.arb_spread_ticks for s in samples], dtype=np.int8,
        )
        pnl_arr = np.array(
            [s.expected_locked_pnl for s in samples], dtype=np.float32,
        )
    else:
        obs_matrix = np.empty((0, obs_dim), dtype=np.float32)
        tick_arr = np.empty(0, dtype=np.int32)
        runner_arr = np.empty(0, dtype=np.int32)
        spread_arr = np.empty(0, dtype=np.int8)
        pnl_arr = np.empty(0, dtype=np.float32)

    np.savez(
        tmp_stem,
        tick_index=tick_arr,
        runner_idx=runner_arr,
        obs=obs_matrix,
        arb_spread_ticks=spread_arr,
        expected_locked_pnl=pnl_arr,
        obs_schema_version=np.array(OBS_SCHEMA_VERSION, dtype=np.int32),
        action_schema_version=np.array(ACTION_SCHEMA_VERSION, dtype=np.int32),
        obs_dim_stored=np.array(obs_dim, dtype=np.int32),
    )
    if path.exists():
        path.unlink()
    tmp.rename(path)


def _save_negative_samples_atomic(
    samples: list[NegativeOracleSample],
    path: Path,
    obs_dim: int,
) -> None:
    """Mirror :func:`_save_samples_atomic` for the negative cache.

    BC label augmentation Phase A. The npz carries (tick_index,
    runner_idx, obs) plus the same schema-version header fields the
    positive cache uses so :func:`load_negative_samples` can strict-
    validate identically.
    """
    tmp_stem = path.parent / (path.stem + "_tmp")
    tmp = path.parent / (path.stem + "_tmp.npz")
    n = len(samples)

    if n > 0:
        obs_matrix = np.stack([s.obs for s in samples]).astype(np.float32)
        tick_arr = np.array([s.tick_index for s in samples], dtype=np.int32)
        runner_arr = np.array([s.runner_idx for s in samples], dtype=np.int32)
    else:
        obs_matrix = np.empty((0, obs_dim), dtype=np.float32)
        tick_arr = np.empty(0, dtype=np.int32)
        runner_arr = np.empty(0, dtype=np.int32)

    np.savez(
        tmp_stem,
        tick_index=tick_arr,
        runner_idx=runner_arr,
        obs=obs_matrix,
        obs_schema_version=np.array(OBS_SCHEMA_VERSION, dtype=np.int32),
        action_schema_version=np.array(ACTION_SCHEMA_VERSION, dtype=np.int32),
        obs_dim_stored=np.array(obs_dim, dtype=np.int32),
    )
    if path.exists():
        path.unlink()
    tmp.rename(path)


def _save_close_hold_samples_atomic(
    samples: list["CloseHoldSample"],
    path: Path,
    obs_dim: int,
) -> None:
    """Mirror :func:`_save_samples_atomic` for the close/hold cache.

    BC label augmentation Phase B. The npz carries (tick_index,
    runner_idx, obs, target_action_class, lifecycle_position) plus
    the same schema-version header fields the positive/negative
    caches use so :func:`load_close_hold_samples` can strict-validate
    identically.
    """
    tmp_stem = path.parent / (path.stem + "_tmp")
    tmp = path.parent / (path.stem + "_tmp.npz")
    n = len(samples)

    if n > 0:
        obs_matrix = np.stack([s.obs for s in samples]).astype(np.float32)
        tick_arr = np.array([s.tick_index for s in samples], dtype=np.int32)
        runner_arr = np.array([s.runner_idx for s in samples], dtype=np.int32)
        target_arr = np.array(
            [s.target_action_class for s in samples], dtype=np.int8,
        )
        lp_arr = np.array(
            [s.lifecycle_position for s in samples], dtype=np.float32,
        )
    else:
        obs_matrix = np.empty((0, obs_dim), dtype=np.float32)
        tick_arr = np.empty(0, dtype=np.int32)
        runner_arr = np.empty(0, dtype=np.int32)
        target_arr = np.empty(0, dtype=np.int8)
        lp_arr = np.empty(0, dtype=np.float32)

    np.savez(
        tmp_stem,
        tick_index=tick_arr,
        runner_idx=runner_arr,
        obs=obs_matrix,
        target_action_class=target_arr,
        lifecycle_position=lp_arr,
        obs_schema_version=np.array(OBS_SCHEMA_VERSION, dtype=np.int32),
        action_schema_version=np.array(ACTION_SCHEMA_VERSION, dtype=np.int32),
        obs_dim_stored=np.array(obs_dim, dtype=np.int32),
    )
    if path.exists():
        path.unlink()
    tmp.rename(path)


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except Exception:
        return "unknown"


def _load_config() -> dict:
    import yaml  # type: ignore[import-untyped]
    with open("config.yaml") as f:
        return yaml.safe_load(f)
